# Generated by Django 5.2.8 on 2025-11-11 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id_chofer', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPasajero',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('fecha_registro', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('chofer_preferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasajeros_preferidos', to='app_uber.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('duracion', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estatus', models.CharField(max_length=20)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='app_uber.chofer')),
                ('pasajeros', models.ManyToManyField(related_name='viajes', to='app_uber.usuariopasajero')),
            ],
        ),
    ]
